version: "2"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./API-main/DataBase:/docker-entrypoint-initdb.d/:ro
    restart: always

  fast:
    build: ./API-main
    links:
      - db
    ports:
      - 5000:5000 #8830 - localhost del host, 5000 del container
    restart: always

  react:
    build: ./frontend
    links:
      - db
    ports:
      - 3000:3000
    restart: always
