DROP DATABASE IF EXISTS SERVER;
CREATE DATABASE SERVER;
USE SERVER;

CREATE TABLE USUARIOS(
    MAIL VARCHAR(45) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(45) NOT NULL,
    CONTRASENA VARCHAR(200) NOT NULL
);